    version: "3.9"

    services:
      db:
        image: mysql
        container_name: CrudDemoApi-db
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: AAAaaa011095
          MYSQL_DATABASE: Study
        volumes:
          - ./dbdata:/var/lib/mysql
        ports:
          - 3306:3306